/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package String.Letter.Count;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void countLetters(String sentence) {
        String sen = sentence;
        String newSen = "";
        int len = sen.length();
        int counter = 0;
        int store = 0;
        char ch;

        while (store < len) {
            for (int i = store; i < len - 1; i++) {
                ch = sen.charAt(store);
                if (ch == sen.charAt(i + 1)) {
                    counter++;
                    store = store + counter;
                    newSen = newSen + sen.charAt(store) + (counter + 1);
                    counter = 0;
                    store++;
                    System.out.println(store + " " + newSen);
                }
//                } else {
//                    counter=1;
//                    store = store + counter;
//                    newSen = newSen + sen.charAt(store) + (counter);
//                    counter = 0;
//                    store++;
//                    System.out.println(store + " " + newSen);
//                }

                if (newSen.length() > sen.length()) System.out.println(sen);
            }
        }
    }

// public static void countLetters(String sentence){
//     String sen = sentence;
//     String senNew = "";
//     int len = sen.length();
//     int counter = 0;
//     int store=0;
//     String letterType = "";
    
//     for (int i=0;i<len;i++){
//         store = 0;
//         if (i<len-1){
//         while (sen.charAt(i)==sen.charAt(i+1)){
//         if (sen.charAt(i)==sen.charAt(i+1)){
//             char ch = sen.charAt(i);
//             store = store + counter;
//             senNew = senNew + ch + store;
//             System.out.println(senNew);
            
            



//         }
//     }
//     }

//     }
    
//}

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        countLetters("aaabbcccc");





    }
}
